'use strict';
const {Game,GOODS,GKEYS,ROLES,BUILDINGS,active,citySpaces,allColonists}=IslaEngine;
let game=null,timer=null;const $=s=>document.querySelector(s);const SAVE_KEY='islaTutorSaveV2';
const ROLE_UI={settler:['🌱','農園を取る'],mayor:['👥','入植者を配置'],builder:['🔨','建物を建てる'],craftsman:['⚙️','商品を生産'],trader:['💰','商品を売る'],captain:['⛵','商品を出荷'],prospector:['⛏️','1金を得る']};
function schedule(fn,ms=120){clearTimeout(timer);timer=setTimeout(fn,ms)}
function save(){if(game)localStorage.setItem(SAVE_KEY,JSON.stringify(game.s))}
function start(opts){clearTimeout(timer);game=new Game(opts);showGame();advance()}
function advance(){try{game.continue();render();save();if(!game.s.pending&&game.s.phase!=='end')schedule(advance)}catch(e){console.error(e);showError('進行中に問題が発生しました。新しいゲームを開始してください。')}}
function act(type,payload={}){try{game.dispatch(type,payload);render();save();if(!game.s.pending&&game.s.phase!=='end')schedule(advance)}catch(e){console.error(e);alert(e.message);render()}}
function showError(msg){$('#decisionBody').innerHTML=`<h2>処理できませんでした</h2><p>${escapeHtml(msg)}</p>`}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showGame(){$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');render()}
function render(){if(!game)return;const s=game.s;$('#roundLabel').textContent=`ラウンド ${s.round}`;const turn=s.phase==='rolePick'?`${escapeHtml(s.players[s.chooser].name)}が役職を選択中`:s.phase==='end'?'ゲーム終了':`${ROLES[s.currentRole]||''}フェーズ`;$('#status').innerHTML=`拡張：<b>なし</b>　｜　総督：<b>${escapeHtml(s.players[s.governor].name)}</b>　｜　${turn}　｜　残りVP <b>${s.vpSupply}</b>　｜　入植者予備 <b>${s.colonistReserve}</b>`;renderRoles();renderCenter();renderBuildingMarket();renderPlayers();renderDecision();$('#coach').innerHTML=`<h3>${escapeHtml(s.coach.title)}</h3><p>${escapeHtml(s.coach.text)}</p>`;$('#log').innerHTML=s.log.map(x=>`<div class="log-item">${escapeHtml(x)}</div>`).join('');if(s.phase==='end')renderEnd()}
function renderRoles(){const s=game.s;$('#roles').innerHTML=s.roles.map(r=>{const enabled=s.pending?.type==='role'&&s.pending.options.includes(r),ui=ROLE_UI[r];return `<button class="role ${enabled?'available':''}" ${enabled?'':'disabled'} data-role="${r}"><span class="role-icon">${ui[0]}</span><span><b>${ROLES[r]}</b><small>${ui[1]}</small></span>${s.roleCoins[r]?`<span class="coins">${s.roleCoins[r]}</span>`:''}</button>`}).join('');document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>act('role',{role:b.dataset.role}))}
function goodChip(g,n=''){return `<span class="good mini ${g}" title="${GOODS[g].name}">${GOODS[g].name[0]}${n}</span>`}
function renderCenter(){const s=game.s;$('#market').innerHTML=s.trade.length?s.trade.map(g=>goodChip(g)).join(''):'<small>商館は空です</small>';$('#ships').innerHTML=s.ships.map((sh,i)=>`<div class="ship"><div class="ship-head"><span>船 ${i+1} ${sh.good?GOODS[sh.good].name:''}</span><b>${sh.qty}/${sh.cap}</b></div><div class="ship-track"><div class="ship-fill" style="width:${sh.qty/sh.cap*100}%"></div></div></div>`).join('')}
function renderBuildingMarket(){const s=game.s,affordableIds=new Set(s.pending?.type==='builder'?s.pending.options.map(b=>b.id):[]);$('#buildingMarket').innerHTML=[1,2,3,4].map(column=>`<section class="building-column"><h3>${column}列</h3>${BUILDINGS.filter(b=>b.column===column).map(b=>{const remaining=s.buildingSupply[b.id],base=s.balanced&&b.id==='factory'?8:s.balanced&&b.id==='university'?7:b.cost;return `<div class="building-stock ${remaining===0?'sold-out':''} ${affordableIds.has(b.id)?'can-build':''}" title="${escapeHtml(buildingText(b))}"><span><b>${escapeHtml(b.name)}</b><small>${base}金・${b.vp}VP</small></span><strong aria-label="残り${remaining}棟">残${remaining}</strong></div>`}).join('')}</section>`).join('')}
function renderPlayers(){const s=game.s;$('#players').innerHTML=s.players.map((p,i)=>{const activeTurn=(s.phase==='rolePick'?s.chooser:s.ctx?.order?.[s.ctx?.pos])===i;return `<article class="player ${p.human?'you':''} ${activeTurn?'active':''}"><div class="player-head"><h3>${escapeHtml(p.name)}</h3><span>${i===s.governor?'<span class="badge">総督</span>':''}${p.human?'<span class="badge">YOU</span>':''}</span></div><div class="stats"><span>金 <b>${p.money}</b></span><span>VP <b>${p.vp}</b></span><span>待機 <b>${p.sanjuan}</b></span><span>都市 <b>${citySpaces(p)}/12</b></span><span>島 <b>${p.plants.length}/12</b></span></div><div class="board">${p.plants.map(x=>`<span class="tile">${x.quarry?'採石場':GOODS[x.good].name}<span class="worker">${x.worker?' ●':''}</span></span>`).join('')}${p.buildings.map(b=>`<span class="tile" title="${escapeHtml(buildingText(b))}">${escapeHtml(b.name)}<span class="worker">${b.workers?` ●${b.workers}`:''}</span></span>`).join('')}</div><div class="goods-row">${GKEYS.filter(g=>p.goods[g]).map(g=>goodChip(g,p.goods[g])).join('')}</div></article>`}).join('')}
function buildingText(b){if(b.kind==='production')return `${GOODS[b.good].name}を最大${b.capacity}個生産`;const m={market1:'売却+1金',hacienda:'裏向き農園を追加取得',construction:'開拓者で採石場を選択可',store1:'1種類を倉庫保管',hospice:'取得地に入植者',office:'商館と同種も売却可',market2:'売却+2金',store2:'2種類を倉庫保管',factory:'多品種生産で収入',university:'新築建物に入植者',harbor:'積載ごと+1VP',wharf:'専用船を使用',guild:'生産建物で追加VP',residence:'島に置いたタイル数で追加VP',fortress:'入植者3人ごと1VP',customs:'出荷VP4ごと1VP',cityhall:'紫建物ごと1VP'};return m[b.effect]||''}
function choiceButton(label,sub,attrs=''){return `<button class="choice" ${attrs}><b>${escapeHtml(label)}</b>${sub?`<small>${escapeHtml(sub)}</small>`:''}</button>`}
function renderDecision(){const el=$('#decisionBody'),p=game.s.pending;if(!p){el.innerHTML=game.s.phase==='end'?'<h2>ゲーム終了</h2><p>最終結果を表示しています。</p>':'<h2>NPCが考えています</h2><p>判断理由は右のコーチ欄に表示されます。</p>';return}if(p.type==='role'){el.innerHTML='<h2>役職を選んでください</h2><p>左の役職から選びます。相手が便乗して得るものにも注目してください。</p>';return}if(p.type==='hacienda'){el.innerHTML=`<h2>農地管理所を使いますか？</h2><p>通常の農園選択より前に、山から裏向きで1枚取ります。</p><div class="choices">${choiceButton('使う','島の空きマスを1つ使います','data-hacienda="1"')}${choiceButton('使わない','表向き農園だけを選びます','data-hacienda="0"')}</div>`;el.querySelectorAll('[data-hacienda]').forEach(b=>b.onclick=()=>act('hacienda',{use:b.dataset.hacienda==='1'}));return}if(p.type==='settler'){el.innerHTML=`<h2>農園または採石場を選ぶ</h2><p>島の空きはあと${12-game.s.players[0].plants.length}マスです。</p><div class="choices">${p.options.map((x,i)=>choiceButton(x.kind==='quarry'?'採石場':`${GOODS[x.good].name}農園`,x.kind==='quarry'?'建物購入を割引':'農園を取得',`data-option="${i}"`)).join('')}</div>`;el.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>act('settler',{choice:p.options[+b.dataset.option]}));return}if(p.type==='staff'){renderStaff(el);return}if(p.type==='builder'){el.innerHTML=`<h2>建物を建てる</h2><p>選択者だけが1金引きになります。採石場割引も反映済みです。</p><div class="choices">${p.options.map(b=>choiceButton(`${b.name}　${b.price}金`,`${b.vp}VP / ${buildingText(b)}`,`data-build="${b.id}"`)).join('')}${choiceButton('見送る','建築しない','data-build=""')}</div>`;el.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>act('builder',{id:b.dataset.build||null}));return}if(p.type==='craftsmanBonus'){el.innerHTML=`<h2>追加生産する商品</h2><p>今回生産した種類から1個を選びます。</p><div class="choices">${p.options.map(g=>choiceButton(GOODS[g].name,'1個追加',`data-good="${g}"`)).join('')}</div>`;el.querySelectorAll('[data-good]').forEach(b=>b.onclick=()=>act('craftsmanBonus',{good:b.dataset.good}));return}if(p.type==='trader'){el.innerHTML=`<h2>商品を売る</h2><p>${p.priv?'あなたが選択者なので、売却できれば特権+1金です。':'便乗のため、商人の+1金特権はありません。'}</p><div class="choices">${p.options.map(g=>choiceButton(`${GOODS[g].name}を売る`,`${salePreview(g,p.priv)}金`,`data-sale="${g}"`)).join('')}${choiceButton('見送る','売却しない','data-sale=""')}</div>`;el.querySelectorAll('[data-sale]').forEach(b=>b.onclick=()=>act('trader',{good:b.dataset.sale||null}));return}if(p.type==='captain'){el.innerHTML=`<h2>商品を出荷する</h2><p>${p.mustShip?'公共船へ積める商品があるため、出荷は必須です。':'造船所は使わず温存できます。'}</p><div class="choices">${p.options.map((x,i)=>choiceButton(`${GOODS[x.good].name}を${x.qty}個出荷`,x.kind==='wharf'?'造船所を使用':`船${x.ship+1}へ最大数を積載`,`data-ship="${i}"`)).join('')}${p.mustShip?'':choiceButton('造船所を使わない','今回は温存する','data-skip-ship')}</div>`;el.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>act('captain',{choice:p.options[+b.dataset.ship]}));el.querySelector('[data-skip-ship]')?.addEventListener('click',()=>act('captain',{choice:null}));return}if(p.type==='storage'){renderStorage(el,p)}}
function salePreview(g,priv){const p=game.s.players[0];return GOODS[g].value+(priv?1:0)+(active(p,'market1')?1:0)+(active(p,'market2')?2:0)}
function renderStaff(el){const p=game.s.players[0],owned=allColonists(p);el.innerHTML=`<h2>入植者を配置</h2><p>合計${owned}人。各マスの＋／－で配置を組み替えます。</p><div class="staff-grid">${p.plants.map((x,i)=>staffRow(x.quarry?'採石場':GOODS[x.good].name+'農園',x.worker,1,'plant',i)).join('')}${p.buildings.map((b,i)=>staffRow(b.name,b.workers,b.slots,'building',i)).join('')}</div><div class="staff-footer">未配置 <b id="staffFree">${p.sanjuan}</b>人 <button class="primary" id="staffDone">配置を確定</button></div>`;el.querySelectorAll('[data-staff]').forEach(b=>b.onclick=()=>staffChange(b.dataset.kind,+b.dataset.index,+b.dataset.delta));$('#staffDone').onclick=submitStaff}
function staffRow(name,n,max,kind,i){return `<div class="staff-row"><span>${escapeHtml(name)}</span><button data-staff data-kind="${kind}" data-index="${i}" data-delta="-1" aria-label="${escapeHtml(name)}から外す">−</button><b>${n}/${max}</b><button data-staff data-kind="${kind}" data-index="${i}" data-delta="1" aria-label="${escapeHtml(name)}に配置">＋</button></div>`}
function staffChange(kind,i,d){const p=game.s.players[0],t=kind==='plant'?p.plants[i]:p.buildings[i],key=kind==='plant'?'worker':'workers',max=kind==='plant'?1:t.slots;if(d>0&&p.sanjuan>0&&t[key]<max){t[key]++;p.sanjuan--}if(d<0&&t[key]>0){t[key]--;p.sanjuan++}renderDecision()}
function submitStaff(){const p=game.s.players[0];act('staff',{plants:p.plants.map(x=>x.worker),buildings:p.buildings.map(b=>b.workers)})}
function renderStorage(el,pending){const p=game.s.players[0];el.innerHTML=`<h2>商品を保管</h2><p>倉庫で最大${pending.warehouseSlots}種類をすべて保管し、さらに別の1種類を1個だけ残せます。</p><form id="storageForm"><div class="storage-list">${pending.types.map(g=>`<label><input type="checkbox" name="protected" value="${g}" ${pending.warehouseSlots?'':'disabled'}><span>${GOODS[g].name} ${p.goods[g]}個を倉庫保管</span></label>`).join('')}</div><label class="loose-label">倉庫外で1個残す<select name="loose"><option value="">残さない</option>${pending.types.map(g=>`<option value="${g}">${GOODS[g].name}</option>`).join('')}</select></label><button class="primary" type="submit">保管を確定</button></form>`;const form=$('#storageForm');form.onchange=()=>{const checked=[...form.querySelectorAll('[name=protected]:checked')];if(checked.length>pending.warehouseSlots)checked[checked.length-1].checked=false};form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);act('storage',{protectedTypes:fd.getAll('protected'),loose:fd.get('loose')||null})}}
function rankedResults(rows){let rank=1;return rows.map((x,i)=>{if(i&&(x.total!==rows[i-1].total||x.tie!==rows[i-1].tie))rank=i+1;return{...x,rank}})}
function renderEnd(){const s=game.s;if($('#endDialog').open)return;const rows=rankedResults(s.result);$('#endBody').innerHTML=`<h2>${rows[0].index===0?'勝利しました！':'ゲーム終了'}</h2><table class="score-table"><tr><th>プレイヤー</th><th>出荷</th><th>建物</th><th>大型</th><th>合計</th></tr>${rows.map(x=>`<tr><td>${x.rank}位 ${escapeHtml(x.name)}</td><td>${escapeHtml(x.shipping)}</td><td>${escapeHtml(x.building)}</td><td>${escapeHtml(x.bonus)}</td><td><b>${escapeHtml(x.total)}</b></td></tr>`).join('')}</table><button class="primary" id="endNew">新しいゲーム</button>`;$('#endDialog').showModal();$('#endNew').onclick=resetToSetup}
function resetToSetup(){clearTimeout(timer);timer=null;game=null;$('#endDialog').open&&$('#endDialog').close();$('#game').classList.add('hidden');$('#setup').classList.remove('hidden');$('#resumeBtn').classList.toggle('hidden',!localStorage.getItem(SAVE_KEY))}
document.querySelectorAll('[name="expansion"]').forEach(x=>x.onchange=()=>$('#expansionNotice').classList.toggle('hidden',document.querySelector('[name="expansion"]:checked')?.value==='none'));
$('#setupForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),expansion=fd.get('expansion');if(expansion!=='none'){$('#expansionNotice').classList.remove('hidden');return}start({count:+fd.get('count'),difficulty:fd.get('difficulty'),balanced:$('#balanced').checked,expansion})};$('#newBtn').onclick=()=>{if(!game||confirm('現在のゲームを終了して設定画面に戻りますか？'))resetToSetup()};$('#rulesBtn').onclick=()=>$('#rulesDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
if(localStorage.getItem(SAVE_KEY)){$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').onclick=()=>{try{game=Game.restore(JSON.parse(localStorage.getItem(SAVE_KEY)));showGame();game.s.phase==='end'?render():advance()}catch(e){localStorage.removeItem(SAVE_KEY);$('#resumeBtn').classList.add('hidden');alert('保存データを読み込めませんでした。新しいゲームを開始してください。')}}}
