(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.IslaEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const GOODS={corn:{name:'トウモロコシ',value:0},indigo:{name:'インディゴ',value:1},sugar:{name:'砂糖',value:2},tobacco:{name:'タバコ',value:3},coffee:{name:'コーヒー',value:4}};
const GKEYS=Object.keys(GOODS);
const ROLES={settler:'開拓者',mayor:'親方',builder:'建築家',craftsman:'監督',trader:'商人',captain:'船長',prospector:'金鉱掘り'};
const BUILDINGS=[
 {id:'sm_indigo',name:'小インディゴ工場',cost:1,vp:1,slots:1,kind:'production',good:'indigo',capacity:1,column:1,smallProduction:true,count:4},
 {id:'sm_sugar',name:'小砂糖工場',cost:2,vp:1,slots:1,kind:'production',good:'sugar',capacity:1,column:1,smallProduction:true,count:4},
 {id:'indigo',name:'インディゴ工場',cost:3,vp:2,slots:3,kind:'production',good:'indigo',capacity:3,column:2,count:3},
 {id:'sugar',name:'砂糖工場',cost:4,vp:2,slots:3,kind:'production',good:'sugar',capacity:3,column:2,count:3},
 {id:'tobacco',name:'タバコ保存所',cost:5,vp:3,slots:3,kind:'production',good:'tobacco',capacity:3,column:3,count:3},
 {id:'coffee',name:'コーヒー焙煎所',cost:6,vp:3,slots:2,kind:'production',good:'coffee',capacity:2,column:3,count:3},
 {id:'small_market',name:'小さい市場',cost:1,vp:1,slots:1,effect:'market1',column:1,violet:true,count:2},
 {id:'hacienda',name:'農地管理所',cost:2,vp:1,slots:1,effect:'hacienda',column:1,violet:true,count:2},
 {id:'construction',name:'建設小屋',cost:2,vp:1,slots:1,effect:'construction',column:1,violet:true,count:2},
 {id:'small_wh',name:'小さい倉庫',cost:3,vp:1,slots:1,effect:'store1',column:1,violet:true,count:2},
 {id:'hospice',name:'救護所',cost:4,vp:2,slots:1,effect:'hospice',column:2,violet:true,count:2},
 {id:'office',name:'商館',cost:5,vp:2,slots:1,effect:'office',column:2,violet:true,count:2},
 {id:'large_market',name:'大きい市場',cost:5,vp:2,slots:1,effect:'market2',column:2,violet:true,count:2},
 {id:'large_wh',name:'大きい倉庫',cost:6,vp:2,slots:1,effect:'store2',column:2,violet:true,count:2},
 {id:'factory',name:'工場',cost:7,vp:3,slots:1,effect:'factory',column:3,violet:true,count:2},
 {id:'university',name:'大学',cost:8,vp:3,slots:1,effect:'university',column:3,violet:true,count:2},
 {id:'harbor',name:'港',cost:8,vp:3,slots:1,effect:'harbor',column:3,violet:true,count:2},
 {id:'wharf',name:'造船所',cost:9,vp:3,slots:1,effect:'wharf',column:3,violet:true,count:2},
 {id:'guild',name:'ギルドホール',cost:10,vp:4,slots:1,effect:'guild',column:4,violet:true,large:true,count:1,citySize:2},
 {id:'residence',name:'公邸',cost:10,vp:4,slots:1,effect:'residence',column:4,violet:true,large:true,count:1,citySize:2},
 {id:'fortress',name:'要塞',cost:10,vp:4,slots:1,effect:'fortress',column:4,violet:true,large:true,count:1,citySize:2},
 {id:'customs',name:'税関',cost:10,vp:4,slots:1,effect:'customs',column:4,violet:true,large:true,count:1,citySize:2},
 {id:'cityhall',name:'市役所',cost:10,vp:4,slots:1,effect:'cityhall',column:4,violet:true,large:true,count:1,citySize:2}
];
const SETUP={2:{vp:65,colonists:40,ships:[4,6],roles:['settler','mayor','builder','craftsman','trader','captain','prospector'],picks:6,starts:['indigo','corn'],removePlant:3,buildingLimit:2},3:{vp:75,colonists:55,ships:[4,5,6],roles:['settler','mayor','builder','craftsman','trader','captain'],picks:3,starts:['indigo','indigo','corn'],removePlant:0},4:{vp:100,colonists:75,ships:[5,6,7],roles:['settler','mayor','builder','craftsman','trader','captain','prospector'],picks:4,starts:['indigo','indigo','corn','corn'],removePlant:0}};
const clone=o=>JSON.parse(JSON.stringify(o));
function shuffle(a,rng=Math.random){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function blankGoods(){return Object.fromEntries(GKEYS.map(g=>[g,0]))}
function active(p,e){return p.buildings.some(b=>b.effect===e&&b.workers>0)}
function citySpaces(p){return p.buildings.reduce((n,b)=>n+(b.citySize||1),0)}
function allColonists(p){return p.sanjuan+p.plants.reduce((n,x)=>n+x.worker,0)+p.buildings.reduce((n,b)=>n+b.workers,0)}
function makeDeck(remove,starts,rng){const counts={corn:10,indigo:12,sugar:11,tobacco:9,coffee:8};GKEYS.forEach(g=>counts[g]-=remove);starts.forEach(g=>counts[g]--);let d=[];GKEYS.forEach(g=>{for(let i=0;i<counts[g];i++)d.push(g)});return shuffle(d,rng)}
function validInt(n,min=0,max=Number.MAX_SAFE_INTEGER){return Number.isInteger(n)&&n>=min&&n<=max}
function validateSnapshot(s){
 if(!s||s.schema!==2||![2,3,4].includes(s.count)||s.expansion!=='none')throw Error('保存データの形式が古いか壊れています');
 const cfg=SETUP[s.count],phases=['rolePick','settler','mayor','builder','craftsman','trader','captain','captainStorage','end'],pendingTypes=['role','hacienda','settler','hospice','mayorBonus','staff','builder','university','craftsmanProduce','craftsmanBonus','trader','captain','captainPrivilege','harbor','storage'];
 if(!phases.includes(s.phase)||!Array.isArray(s.players)||s.players.length!==s.count||JSON.stringify(s.roles)!==JSON.stringify(cfg.roles)||!Array.isArray(s.chosen)||s.chosen.length>cfg.picks||s.chosen.some(r=>!s.roles.includes(r))||new Set(s.chosen).size!==s.chosen.length)throw Error('保存データの進行状態が壊れています');
 if(s.pending&&(!pendingTypes.includes(s.pending.type)||typeof s.pending!=='object'))throw Error('保存データの選択状態が壊れています');
 for(const key of ['round','governor','chooser','pickLimit','colonistReserve','colonistShip','quarries','vpSupply'])if(!validInt(s[key]))throw Error('保存データの数値が壊れています');
 if(s.governor>=s.count||s.chooser>=s.count||s.pickLimit!==cfg.picks||!['easy','normal','hard'].includes(s.difficulty)||typeof s.balanced!=='boolean'||typeof s.endAfterRound!=='boolean'||!s.goodsSupply||!s.roleCoins||!s.buildingSupply)throw Error('保存データの準備状態が壊れています');
 s.roles.forEach(r=>{if(!validInt(s.roleCoins[r]))throw Error('役職金データが壊れています')});
 if(['settler','builder','craftsman','trader','captain','captainStorage'].includes(s.phase)&&(!s.ctx||typeof s.ctx!=='object'))throw Error('保存データのフェーズ情報が壊れています');
 const names=['あなた','NPC アナ','NPC ベル','NPC カルロ'];
 s.players.forEach((p,i)=>{if(p.name!==names[i]||p.human!==(i===0)||typeof p.wharfUsed!=='boolean'||!validInt(p.money)||!validInt(p.vp)||!validInt(p.sanjuan)||!Array.isArray(p.plants)||p.plants.length>12||!Array.isArray(p.buildings)||citySpaces(p)>12||!p.goods)throw Error('プレイヤーデータが壊れています');const ids=new Set();p.plants.forEach(x=>{if(!x||!validInt(x.worker,0,1)||(!x.quarry&&!GKEYS.includes(x.good))||(x.quarry&&x.good!==null))throw Error('農園データが壊れています')});p.buildings.forEach(b=>{const d=BUILDINGS.find(x=>x.id===b.id),canonical=d?{...clone(d),workers:b.workers}:null;if(!d||ids.has(b.id)||!validInt(b.workers,0,d.slots)||JSON.stringify(b)!==JSON.stringify(canonical)){throw Error('建物データが壊れています')}ids.add(b.id)});GKEYS.forEach(g=>{if(!validInt(p.goods[g]))throw Error('商品データが壊れています')})});
 GKEYS.forEach(g=>{if(!validInt(s.goodsSupply[g]))throw Error('商品供給が壊れています')});if(!Array.isArray(s.trade)||s.trade.length>4||s.trade.some(g=>!GKEYS.includes(g)))throw Error('商館データが壊れています');
 if(!Array.isArray(s.ships)||s.ships.length!==cfg.ships.length)s.ships=[];if(s.ships.length!==cfg.ships.length)throw Error('船データが壊れています');s.ships.forEach((sh,i)=>{if(sh.id!==i||sh.cap!==cfg.ships[i]||!validInt(sh.qty,0,sh.cap)||(sh.qty===0?sh.good!==null:!GKEYS.includes(sh.good)))throw Error('船データが壊れています')});
 const expectedGoods={corn:10,indigo:11,sugar:11,tobacco:9,coffee:9};if(s.count===2)GKEYS.forEach(g=>expectedGoods[g]-=2);GKEYS.forEach(g=>{const total=s.goodsSupply[g]+s.players.reduce((n,p)=>n+p.goods[g],0)+s.trade.filter(x=>x===g).length+s.ships.filter(x=>x.good===g).reduce((n,x)=>n+x.qty,0);if(total!==expectedGoods[g])throw Error('商品の総数が一致しません')});
 const colonists=s.colonistReserve+s.colonistShip+s.players.reduce((n,p)=>n+allColonists(p),0);if(colonists!==cfg.colonists+s.count)throw Error('入植者の総数が一致しません');
 for(const pile of [s.plantDeck,s.plantDiscard,s.faceup])if(!Array.isArray(pile)||pile.some(g=>!GKEYS.includes(g)))throw Error('農園データが壊れています');
 const remove=cfg.removePlant,plantCount=s.plantDeck.length+s.plantDiscard.length+s.faceup.length+s.players.reduce((n,p)=>n+p.plants.filter(x=>!x.quarry).length,0),quarryCount=s.quarries+s.players.reduce((n,p)=>n+p.plants.filter(x=>x.quarry).length,0);if(plantCount!==50-remove*5||quarryCount!==8-remove)throw Error('農園・採石場の総数が一致しません');
 BUILDINGS.forEach(b=>{const expected=s.count===2?(b.large?1:(b.violet?1:2)):b.count,total=s.buildingSupply[b.id]+s.players.reduce((n,p)=>n+p.buildings.filter(x=>x.id===b.id).length,0);if(!validInt(s.buildingSupply[b.id])||total!==expected)throw Error('建物の総数が一致しません')});if(!Array.isArray(s.log)||s.log.length>80||s.log.some(x=>typeof x!=='string')||!s.coach||typeof s.coach.title!=='string'||typeof s.coach.text!=='string')throw Error('表示データが壊れています');return true
}
class Game{
 constructor(opts={}){this.rng=opts.rng||Math.random;this.s=this.create(opts)}
 create({count=3,difficulty='normal',balanced=true,expansion='none'}={}){const cfg=SETUP[count];if(!cfg)throw Error('unsupported player count');if(expansion!=='none')throw Error('拡張「新建物」は現在準備中です');const names=['あなた','NPC アナ','NPC ベル','NPC カルロ'];const players=Array.from({length:count},(_,i)=>({name:names[i],human:i===0,money:count===3?2:3,vp:0,plants:[{good:cfg.starts[i],quarry:false,worker:0}],buildings:[],goods:blankGoods(),sanjuan:0,wharfUsed:false}));if(balanced)players.forEach((p,i)=>{if(cfg.starts[i]==='corn')p.money--});const goods={corn:10,indigo:11,sugar:11,tobacco:9,coffee:9};if(count===2)GKEYS.forEach(g=>goods[g]-=2);const available={};BUILDINGS.forEach(b=>available[b.id]=count===2?(b.large?1:(b.violet?1:2)):b.count);const s={schema:2,count,difficulty,balanced,expansion,round:1,governor:0,chooser:0,roles:[...cfg.roles],pickLimit:cfg.picks,roleCoins:Object.fromEntries(cfg.roles.map(r=>[r,0])),chosen:[],players,plantDeck:makeDeck(cfg.removePlant,cfg.starts,this.rng),plantDiscard:[],faceup:[],quarries:8-cfg.removePlant,buildingSupply:available,colonistReserve:cfg.colonists,colonistShip:count,goodsSupply:goods,vpSupply:cfg.vp,trade:[],ships:cfg.ships.map((cap,id)=>({id,cap,good:null,qty:0})),phase:'rolePick',pending:null,ctx:null,endAfterRound:false,log:[],coach:{title:'最初の一手',text:'自分の利益と、相手が便乗して得る利益を比べましょう。'},result:null};this.s=s;this.refillFaceup();this.note('ゲームを開始しました（拡張なし）');return s}
 static restore(data,opts={}){const copy=clone(data);if(copy?.expansion===undefined)copy.expansion='none';if(!Array.isArray(copy?.plantDiscard))copy.plantDiscard=[];validateSnapshot(copy);copy.players.forEach(p=>p.buildings=p.buildings.map(b=>({...clone(BUILDINGS.find(d=>d.id===b.id)),workers:b.workers})));const g=Object.create(Game.prototype);g.rng=opts.rng||Math.random;g.s=copy;g.validateProgress();if(copy.phase==='end')copy.result=g.resultRows();else copy.result=null;return g}
 validateProgress(){
  const s=this.s,t=s.pending?.type||null,allowed={rolePick:[null,'role'],mayor:['mayorBonus','staff'],settler:[null,'hacienda','settler','hospice'],builder:[null,'builder','university'],craftsman:[null,'craftsmanProduce','craftsmanBonus'],trader:[null,'trader'],captain:[null,'captain','captainPrivilege','harbor'],captainStorage:[null,'storage'],end:[null]};
  if(!allowed[s.phase].includes(t))throw Error('保存データの選択状態がフェーズと一致しません');
  if(s.phase==='rolePick'){if(s.ctx!==null||s.chosen.length>=s.pickLimit)throw Error('保存データの役職選択状態が壊れています');if(t==='role'&&(s.chooser!==0||JSON.stringify(s.pending.options)!==JSON.stringify(s.roles.filter(r=>!s.chosen.includes(r)))))throw Error('保存データの役職候補が壊れています');return true}
  if(s.phase==='end'){if(s.ctx!==null||s.chosen.length<s.pickLimit||!(s.endAfterRound||s.vpSupply<=0||s.players.some(p=>citySpaces(p)>=12)))throw Error('保存データの終了状態が壊れています');return true}
  if(!s.roles.includes(s.currentRole)||!s.chosen.includes(s.currentRole)||!validInt(s.currentChooser,0,s.count-1))throw Error('保存データの役職進行が壊れています');
  if(s.phase==='mayor'){if(s.currentRole!=='mayor'||(t==='mayorBonus'&&(s.currentChooser!==0||s.colonistReserve<=0))||(t==='staff'&&s.pending.player!==0))throw Error('保存データの親方状態が壊れています');return true}
  const expectedRole=s.phase==='captainStorage'?'captain':s.phase;if(s.currentRole!==expectedRole||!s.ctx||JSON.stringify(s.ctx.order)!==JSON.stringify(this.order(s.currentChooser)))throw Error('保存データの手番順が壊れています');const c=s.ctx;
  if(s.phase==='captainStorage'){const types=GKEYS.filter(g=>s.players[0].goods[g]>0),slots=(active(s.players[0],'store1')?1:0)+(active(s.players[0],'store2')?2:0);if(!validInt(c.storagePos,0,s.count)||(t==='storage'&&(c.storagePos!==0||JSON.stringify(s.pending.types)!==JSON.stringify(types)||s.pending.warehouseSlots!==slots)))throw Error('保存データの保管状態が壊れています');return true}
  if(!validInt(c.pos,0,s.count))throw Error('保存データの手番位置が壊れています');
  if(['hacienda','settler','hospice','builder','university','craftsmanProduce','trader','captain'].includes(t)&&c.order[c.pos]!==0)throw Error('保存データの人間手番が壊れています');
  if(t==='hacienda'&&(s.pending.player!==0||c.stage!=='main'||!active(s.players[0],'hacienda')))throw Error('保存データの農地管理所状態が壊れています');
  if(t==='settler'){const quarry=(s.currentChooser===0||active(s.players[0],'construction'))&&s.quarries>0,options=s.faceup.map((g,index)=>({kind:'plant',index,good:g}));if(quarry)options.push({kind:'quarry'});if(c.stage!=='choose'||JSON.stringify(s.pending.options)!==JSON.stringify(options))throw Error('保存データの開拓候補が壊れています')}
  if(t==='hospice'&&(!active(s.players[0],'hospice')||!validInt(c.lastPlant,0,s.players[0].plants.length-1)))throw Error('保存データの救護所状態が壊れています');
  if(t==='builder'&&JSON.stringify(s.pending.options)!==JSON.stringify(this.affordable(0,s.currentChooser===0)))throw Error('保存データの建築候補が壊れています');
  if(t==='university'&&(!active(s.players[0],'university')||!validInt(c.lastBuilding,0,s.players[0].buildings.length-1)))throw Error('保存データの大学状態が壊れています');
  if(t==='craftsmanProduce'&&(c.stage!=='produce'||s.pending.player!==0))throw Error('保存データの生産状態が壊れています');
  if(t==='craftsmanBonus'){const options=GKEYS.filter(g=>c.made?.[s.currentChooser]?.[g]>0&&s.goodsSupply[g]>0);if(s.currentChooser!==0||c.stage!=='bonus'||JSON.stringify(s.pending.options)!==JSON.stringify(options))throw Error('保存データの生産特権状態が壊れています')}
  if(t==='trader'&&(JSON.stringify(s.pending.options)!==JSON.stringify(this.saleOptions(0))||s.pending.priv!==(s.currentChooser===0)))throw Error('保存データの売却候補が壊れています');
  if(t==='captain'){const pub=this.publicShipments(0),options=[...pub,...this.wharfShipments(0)];if(JSON.stringify(s.pending.options)!==JSON.stringify(options)||s.pending.mustShip!==(pub.length>0))throw Error('保存データの出荷候補が壊れています')}
  if(t==='captainPrivilege'&&(!c.postShip?.captainEligible||c.order[c.pos]!==0||s.currentChooser!==0))throw Error('保存データの船長特権状態が壊れています');
  if(t==='harbor'&&(!c.postShip?.harborEligible||!active(s.players[0],'harbor')||c.order[c.pos]!==0))throw Error('保存データの港状態が壊れています');return true
 }
 note(x){this.s.log.unshift(x);this.s.log=this.s.log.slice(0,80)}
 explain(title,text){this.s.coach={title,text};this.note(`判断理由：${text}`)}
 order(start){return Array.from({length:this.s.count},(_,i)=>(start+i)%this.s.count)}
 refillFaceup(){const s=this.s;while(s.faceup.length<s.count+1){if(!s.plantDeck.length&&s.plantDiscard.length)s.plantDeck=shuffle(s.plantDiscard.splice(0),this.rng);if(!s.plantDeck.length)break;s.faceup.push(s.plantDeck.shift())}}
 has(p,e){return active(p,e)}
 continue(){let guard=0;while(!this.s.pending&&this.s.phase!=='end'&&guard++<1000){if(this.s.phase==='rolePick')this.rolePickStep();else if(this.s.phase==='settler')this.settlerStep();else if(this.s.phase==='builder')this.builderStep();else if(this.s.phase==='craftsman')this.craftsmanStep();else if(this.s.phase==='trader')this.traderStep();else if(this.s.phase==='captain')this.captainStep();else if(this.s.phase==='captainStorage')this.storageStep();else throw Error('unknown phase '+this.s.phase)}if(guard>=1000)throw Error('state loop')}
 dispatch(type,payload={}){const before=clone(this.s),p=this.s.pending;if(!p||p.type!==type)throw Error('現在はその操作を選べません');this.s.pending=null;const fn=this['on_'+type];if(!fn){this.s=before;throw Error('unknown action')}try{fn.call(this,payload);this.continue()}catch(e){this.s=before;throw e}}
 rolePickStep(){const s=this.s,p=s.players[s.chooser];if(p.human){s.pending={type:'role',options:s.roles.filter(r=>!s.chosen.includes(r))};s.coach={title:'役職を選択',text:this.roleAdvice()};return}this.selectRole(this.aiRole(s.chooser))}
 on_role({role}){if(!this.s.pending===null)return;this.selectRole(role)}
 selectRole(role){const s=this.s;if(s.chosen.includes(role)||!s.roles.includes(role))throw Error('invalid role');const idx=s.chooser,p=s.players[idx],coins=s.roleCoins[role];p.money+=coins;s.roleCoins[role]=0;s.chosen.push(role);s.currentRole=role;s.currentChooser=idx;this.note(`${p.name}が「${ROLES[role]}」を選択${coins?`（${coins}金）`:''}`);this.explain(`${p.name}の選択`,this.explainRole(role,idx));if(role==='prospector'){p.money++;this.note(`${p.name}が1金を獲得`);this.finishRole();return}if(role==='mayor'){this.startMayor();return}if(role==='craftsman'){this.startCraftsman();return}s.phase=role;s.ctx={order:this.order(idx),pos:0,stage:'main',passes:0,captainBonus:{},captainPrivilegeResolved:{},storagePos:0}}
 finishRole(){const s=this.s;if(s.currentRole==='settler'){s.plantDiscard.push(...s.faceup);s.faceup=[];this.refillFaceup()}if(s.currentRole==='trader'&&s.trade.length===4){s.trade.forEach(g=>s.goodsSupply[g]++);s.trade=[];this.note('商館が満杯になり、商品を供給へ戻しました')}s.players.forEach(p=>p.wharfUsed=false);s.chooser=(s.chooser+1)%s.count;s.ctx=null;s.pending=null;if(s.chosen.length>=s.pickLimit)this.endRound();else s.phase='rolePick'}
 endRound(){const s=this.s;s.roles.filter(r=>!s.chosen.includes(r)).forEach(r=>s.roleCoins[r]++);if(s.endAfterRound||s.vpSupply<=0||s.players.some(p=>citySpaces(p)>=12)){this.finishGame();return}s.round++;s.governor=(s.governor+1)%s.count;s.chooser=s.governor;s.chosen=[];s.phase='rolePick';this.note(`ラウンド${s.round}開始。総督は${s.players[s.governor].name}`)}
 settlerStep(){const s=this.s,c=s.ctx;if(c.pos>=c.order.length){this.finishRole();return}const i=c.order[c.pos],p=s.players[i];if(p.plants.length>=12){c.pos++;c.stage='main';return}if(c.stage==='main'&&active(p,'hacienda')){if(p.human){s.pending={type:'hacienda',player:i};return}if(this.aiUseHacienda(i))this.takeHacienda(i);c.stage='choose';return}c.stage='choose';const quarry=(i===s.currentChooser||active(p,'construction'))&&s.quarries>0;const opts=s.faceup.map((g,index)=>({kind:'plant',index,good:g}));if(quarry)opts.push({kind:'quarry'});if(p.human){s.pending={type:'settler',options:opts,canPass:true};return}const choice=this.aiSettler(i,opts);if(choice){this.takeSettler(i,choice);this.explain(`${p.name}の開拓`,choice.kind==='quarry'?'今後の高額建物を安くするため、採石場を選びました。':`稼働中・建設予定の施設と相性がよい${GOODS[choice.good].name}農園を選びました。`)}c.pos++;c.stage='main'}
 on_hacienda({use}){if(typeof use!=='boolean')throw Error('農地管理所の選択が正しくありません');if(use)this.takeHacienda(0);this.s.ctx.stage='choose'}
 drawPlant(){const s=this.s;if(!s.plantDeck.length&&s.plantDiscard.length)s.plantDeck=shuffle(s.plantDiscard.splice(0),this.rng);return s.plantDeck.shift()||null}
 takeHacienda(i){const s=this.s,p=s.players[i];if(p.plants.length>=12)return;const g=this.drawPlant();if(!g)return;p.plants.push({good:g,quarry:false,worker:0});this.note(`${p.name}が農地管理所で裏向き農園を獲得`)}
 on_settler({choice}){const s=this.s;if(choice===null){s.ctx.pos++;s.ctx.stage='main';this.note('あなたは開拓を見送りました');return}if(!choice||typeof choice!=='object')throw Error('開拓先の選択が正しくありません');this.takeSettler(0,choice,false);if(active(s.players[0],'hospice')&&this.effectColonistAvailable()){s.ctx.lastPlant=s.players[0].plants.length-1;s.pending={type:'hospice'};return}s.ctx.pos++;s.ctx.stage='main'}
 on_hospice({use}){if(typeof use!=='boolean')throw Error('救護所の選択が正しくありません');const s=this.s;if(use&&this.takeEffectColonist()){s.players[0].plants[s.ctx.lastPlant].worker=1;this.note('救護所で入植者を配置')}s.ctx.pos++;s.ctx.stage='main'}
 effectColonistAvailable(){return this.s.colonistReserve>0||this.s.colonistShip>0}
 takeEffectColonist(){const s=this.s;if(s.colonistReserve>0){s.colonistReserve--;return true}if(s.colonistShip>0){s.colonistShip--;return true}return false}
 takeSettler(i,ch,useEffect=true){const s=this.s,p=s.players[i];if(!ch||p.plants.length>=12)throw Error('illegal settlement');if(ch.kind==='quarry'){const allowed=(i===s.currentChooser||active(p,'construction'))&&s.quarries>0;if(!allowed)throw Error('採石場を選べません');s.quarries--;p.plants.push({good:null,quarry:true,worker:0})}else{if(ch.kind!=='plant'||!Number.isInteger(ch.index)||ch.index<0||ch.index>=s.faceup.length)throw Error('農園を選べません');const [g]=s.faceup.splice(ch.index,1);p.plants.push({good:g,quarry:false,worker:0})}const t=p.plants[p.plants.length-1];if(useEffect&&active(p,'hospice')&&this.takeEffectColonist())t.worker=1;this.note(`${p.name}が${t.quarry?'採石場':GOODS[t.good].name+'農園'}を獲得`)}
 startMayor(){const s=this.s,start=s.currentChooser;let n=s.colonistShip;s.colonistShip=0;let at=start;while(n-->0){s.players[at].sanjuan++;at=(at+1)%s.count}s.phase='mayor';if(s.players[start].human&&s.colonistReserve>0){s.pending={type:'mayorBonus'};return}if(s.colonistReserve>0){s.colonistReserve--;s.players[start].sanjuan++;this.note(`${s.players[start].name}が特権で入植者1人を獲得`)}this.beginStaffing()}
 on_mayorBonus({take}){if(typeof take!=='boolean')throw Error('親方特権の選択が正しくありません');const s=this.s;if(take&&s.colonistReserve>0){s.colonistReserve--;s.players[0].sanjuan++;this.note('あなたが特権で入植者1人を獲得')}this.beginStaffing()}
 beginStaffing(){const s=this.s;s.players.forEach((p,i)=>{if(!p.human)this.autoStaff(i)});s.phase='mayor';s.pending={type:'staff',player:0};s.coach={title:'入植者を配置',text:'インディゴなどは「農園＋対応工場」の両方に配置すると生産できます。トウモロコシだけは農園のみで生産できます。配置は何度でも組み替えられます。'}}
 on_staff({plants,buildings}){const s=this.s,p=s.players[0];if(!Array.isArray(plants)||plants.length!==p.plants.length||!Array.isArray(buildings)||buildings.length!==p.buildings.length)throw Error('配置データが正しくありません');if(plants.some(n=>!validInt(n,0,1))||buildings.some((n,i)=>!validInt(n,0,p.buildings[i].slots)))throw Error('各マスの上限を超えて配置できません');const total=plants.reduce((a,b)=>a+b,0)+buildings.reduce((a,b)=>a+b,0);const owned=allColonists(p),capacity=p.plants.length+p.buildings.reduce((n,b)=>n+b.slots,0),required=Math.min(owned,capacity);if(total>owned)throw Error('所有数を超えて配置できません');if(total<required)throw Error('空きマスがある間は、可能な限り入植者を配置してください');p.plants.forEach((x,i)=>x.worker=plants[i]);p.buildings.forEach((b,i)=>b.workers=buildings[i]);p.sanjuan=owned-total;this.refillColonistShip();this.finishRole()}
 autoStaff(i){const p=this.s.players[i];const clear=()=>{p.plants.forEach(x=>x.worker=0);p.buildings.forEach(b=>b.workers=0)};const owned=allColonists(p);clear();p.sanjuan=owned;const place=t=>{if(p.sanjuan<=0)return false;if('workers'in t){if(t.workers>=t.slots)return false;t.workers++}else{if(t.worker)return false;t.worker=1}p.sanjuan--;return true};for(const g of GKEYS){const farms=p.plants.filter(x=>x.good===g&&!x.quarry);const facs=p.buildings.filter(b=>b.kind==='production'&&b.good===g);for(let k=0;k<(g==='corn'?farms.length:Math.min(farms.length,facs.reduce((n,b)=>n+b.slots,0)));k++){place(farms[k]);if(g!=='corn'){let f=facs.find(b=>b.workers<b.slots);if(f)place(f)}}}p.buildings.filter(b=>b.violet).sort((a,b)=>this.buildingUtility(p,b)-this.buildingUtility(p,a)).forEach(place);p.plants.filter(x=>!x.worker).forEach(place);p.buildings.forEach(b=>{while(place(b)){}})}
 refillColonistShip(){const s=this.s;let need=Math.max(s.count,s.players.reduce((n,p)=>n+p.buildings.reduce((z,b)=>z+(b.slots-b.workers),0),0));if(s.colonistReserve<need)s.endAfterRound=true;const moved=Math.min(need,s.colonistReserve);s.colonistReserve-=moved;s.colonistShip=moved;this.note(`入植船に${moved}人を補充${moved<need?'（不足：ゲーム終了条件）':''}`)}
 builderStep(){const s=this.s,c=s.ctx;if(c.pos>=c.order.length){this.finishRole();return}const i=c.order[c.pos],p=s.players[i],priv=i===s.currentChooser;const opts=this.affordable(i,priv);if(p.human){s.pending={type:'builder',options:opts,canPass:true};return}const id=this.aiBuild(i,opts);if(id){this.buyBuilding(i,id,priv);const b=BUILDINGS.find(x=>x.id===id);this.explain(`${p.name}の建築`,`所持金と農園構成から、今後の収入・得点につながる${b.name}を優先しました。`)}c.pos++}
 on_builder({id}){const s=this.s;if(id===null){s.ctx.pos++;return}if(typeof id!=='string')throw Error('建物の選択が正しくありません');const hadUniversity=active(s.players[0],'university');this.buyBuilding(0,id,s.currentChooser===0,false);if(hadUniversity&&this.effectColonistAvailable()){s.ctx.lastBuilding=s.players[0].buildings.length-1;s.pending={type:'university'};return}s.ctx.pos++}
 on_university({use}){if(typeof use!=='boolean')throw Error('大学の選択が正しくありません');const s=this.s;if(use&&this.takeEffectColonist()){s.players[0].buildings[s.ctx.lastBuilding].workers=1;this.note('大学で新築建物に入植者を配置')}s.ctx.pos++}
 price(i,b,priv){const p=this.s.players[i];let base=b.cost;if(this.s.balanced&&b.id==='factory')base=8;if(this.s.balanced&&b.id==='university')base=7;const quarries=p.plants.filter(x=>x.quarry&&x.worker).length;return Math.max(0,base-(priv?1:0)-Math.min(quarries,b.column))}
 affordable(i,priv){const p=this.s.players[i];return BUILDINGS.filter(b=>this.s.buildingSupply[b.id]>0&&!p.buildings.some(x=>x.id===b.id)&&citySpaces(p)+(b.citySize||1)<=12&&this.price(i,b,priv)<=p.money).map(b=>({...clone(b),price:this.price(i,b,priv)}))}
 buyBuilding(i,id,priv,useEffect=true){const s=this.s,p=s.players[i],def=BUILDINGS.find(b=>b.id===id);if(!def||!validInt(s.buildingSupply[id],1))throw Error('building unavailable');if(p.buildings.some(b=>b.id===id))throw Error('同じ建物は建てられません');if(citySpaces(p)+(def.citySize||1)>12)throw Error('都市の空きマスが足りません');const cost=this.price(i,def,priv);if(cost>p.money)throw Error('cannot afford');p.money-=cost;const hadUniversity=active(p,'university');const b={...clone(def),workers:0};p.buildings.push(b);s.buildingSupply[id]--;if(useEffect&&hadUniversity&&this.takeEffectColonist())b.workers=1;this.note(`${p.name}が${b.name}を${cost}金で建築`)}
 startCraftsman(){const s=this.s;s.phase='craftsman';s.ctx={order:this.order(s.currentChooser),pos:0,made:{},stage:'produce'};this.craftsmanStep()}
 craftsmanStep(){const s=this.s,c=s.ctx;if(c.stage==='produce'&&c.pos<c.order.length){const i=c.order[c.pos],p=s.players[i];if(p.human){s.pending={type:'craftsmanProduce',player:i};return}c.made[i]=this.produce(i);c.pos++;return}if(c.stage==='produce'){c.stage='bonus';const i=s.currentChooser,types=GKEYS.filter(g=>c.made[i]?.[g]>0&&s.goodsSupply[g]>0);if(types.length&&s.players[i].human){s.pending={type:'craftsmanBonus',options:types,canPass:true};return}if(types.length){const g=this.aiGood(i,types);s.players[i].goods[g]++;s.goodsSupply[g]--;this.note(`${s.players[i].name}が特権で${GOODS[g].name}を追加生産`)}this.finishRole()}}
 on_craftsmanProduce({produce}){if(typeof produce!=='boolean')throw Error('生産の選択が正しくありません');const s=this.s,c=s.ctx,i=c.order[c.pos];if(i!==0)throw Error('生産順が正しくありません');c.made[i]=produce?this.produce(i):blankGoods();if(!produce)this.note('あなたは生産を見送りました');c.pos++}
 on_craftsmanBonus({good}){const s=this.s,c=s.ctx;if(good===null){this.finishRole();return}const allowed=GKEYS.filter(g=>c.made[s.currentChooser]?.[g]>0&&s.goodsSupply[g]>0);if(!allowed.includes(good))throw Error('今回生産した商品から選んでください');s.players[0].goods[good]++;s.goodsSupply[good]--;this.note(`あなたが特権で${GOODS[good].name}を追加生産`);this.finishRole()}
 produce(i){const s=this.s,p=s.players[i],made=blankGoods();for(const g of GKEYS){const farms=p.plants.filter(x=>x.worker&&x.good===g).length;const cap=g==='corn'?farms:p.buildings.filter(b=>b.kind==='production'&&b.good===g).reduce((n,b)=>n+b.workers,0);const qty=Math.min(farms,cap,s.goodsSupply[g]);if(qty){p.goods[g]+=qty;s.goodsSupply[g]-=qty;made[g]=qty}}const types=GKEYS.filter(g=>made[g]).length;if(active(p,'factory')&&types>1){const income=[0,0,1,2,3,5][types];p.money+=income;this.note(`${p.name}が工場で${income}金を獲得`)}this.note(`${p.name}が${GKEYS.filter(g=>made[g]).map(g=>`${GOODS[g].name}${made[g]}`).join('・')||'商品なし'}を生産`);return made}
 traderStep(){const s=this.s,c=s.ctx;if(c.pos>=c.order.length){this.finishRole();return}const i=c.order[c.pos],p=s.players[i],opts=this.saleOptions(i),priv=i===s.currentChooser;if(p.human){s.pending={type:'trader',options:opts,canPass:true,priv};return}const g=this.aiSell(i,opts);if(g){this.sell(i,g,priv);const reason=s.difficulty==='easy'?'選べる商品の先頭から売り、次の建築資金を確保しました。':`売値の高い${GOODS[g].name}を現金化し、次の建築資金を確保しました。`;this.explain(`${p.name}の売却`,reason)}c.pos++}
 saleOptions(i){const s=this.s,p=s.players[i];if(s.trade.length>=4)return[];return GKEYS.filter(g=>p.goods[g]>0&&(!s.trade.includes(g)||active(p,'office')))}
 on_trader({good}){if(good!==null&&!GKEYS.includes(good))throw Error('売却商品の選択が正しくありません');if(good)this.sell(0,good,this.s.currentChooser===0);this.s.ctx.pos++}
 sell(i,g,priv){const s=this.s,p=s.players[i];if(!this.saleOptions(i).includes(g))throw Error('illegal sale');p.goods[g]--;s.trade.push(g);const money=GOODS[g].value+(priv?1:0)+(active(p,'market1')?1:0)+(active(p,'market2')?2:0);p.money+=money;this.note(`${p.name}が${GOODS[g].name}を売り${money}金獲得`)}
 captainStep(){const s=this.s,c=s.ctx;if(!c.captainBonus)c.captainBonus={};if(!c.captainPrivilegeResolved)c.captainPrivilegeResolved={};if(c.pos>=c.order.length)c.pos=0;const i=c.order[c.pos],p=s.players[i],pub=this.publicShipments(i),wharf=this.wharfShipments(i);if(!pub.length&&!wharf.length){c.passes++;c.pos++;if(c.passes>=s.count)this.beginStorage();return}if(p.human){s.pending={type:'captain',options:[...pub,...wharf],mustShip:pub.length>0};return}let pick=this.aiShip(i,pub,wharf);if(pick){this.ship(i,pick);c.passes=0;this.explain(`${p.name}の出荷`,`一度に${pick.qty}個積める${GOODS[pick.good].name}を優先し、保管損失を抑えました。`)}else c.passes++;c.pos++;if(c.passes>=s.count)this.beginStorage()}
 publicShipments(i){const s=this.s,p=s.players[i],out=[];for(const g of GKEYS){if(!p.goods[g])continue;const carrying=s.ships.find(sh=>sh.good===g);let choices=carrying?(carrying.qty<carrying.cap?[carrying]:[]):s.ships.filter(sh=>sh.good===null);choices=choices.map(sh=>({kind:'ship',good:g,ship:sh.id,qty:Math.min(p.goods[g],sh.cap-sh.qty)})).filter(x=>x.qty>0);const max=Math.max(0,...choices.map(x=>x.qty));out.push(...choices.filter(x=>x.qty===max))}return out}
 wharfShipments(i){const p=this.s.players[i];if(!active(p,'wharf')||p.wharfUsed)return[];return GKEYS.filter(g=>p.goods[g]>0).map(g=>({kind:'wharf',good:g,qty:p.goods[g]}))}
 on_captain({choice}){const s=this.s,c=s.ctx,pub=this.publicShipments(0);if(choice===null){if(pub.length)throw Error('must ship');this.finishCaptainTurn(false);return}if(!choice||typeof choice!=='object')throw Error('出荷の選択が正しくありません');const captainEligible=s.currentChooser===0&&!c.captainPrivilegeResolved?.[0],harborEligible=active(s.players[0],'harbor');this.ship(0,choice,false,false);c.postShip={captainEligible,harborEligible};this.nextShippingBonus()}
 nextShippingBonus(){const s=this.s,c=s.ctx;if(c.postShip?.captainEligible){s.pending={type:'captainPrivilege'};return}if(c.postShip?.harborEligible){s.pending={type:'harbor'};return}delete c.postShip;this.finishCaptainTurn(true)}
 on_captainPrivilege({use}){if(typeof use!=='boolean')throw Error('船長特権の選択が正しくありません');const s=this.s,c=s.ctx,p=s.players[0];if(!c.postShip?.captainEligible||s.currentChooser!==0)throw Error('船長特権を使える状態ではありません');c.captainPrivilegeResolved[0]=true;c.postShip.captainEligible=false;if(use){p.vp++;s.vpSupply=Math.max(0,s.vpSupply-1);c.captainBonus[0]=true;this.note('あなたが船長特権で1VPを獲得')}this.nextShippingBonus()}
 on_harbor({use}){if(typeof use!=='boolean')throw Error('港の選択が正しくありません');const s=this.s,c=s.ctx,p=s.players[0];if(!c.postShip?.harborEligible||!active(p,'harbor'))throw Error('港を使える状態ではありません');c.postShip.harborEligible=false;if(use){p.vp++;s.vpSupply=Math.max(0,s.vpSupply-1);this.note('あなたが港を使い1VPを獲得')}this.nextShippingBonus()}
 finishCaptainTurn(shipped){const c=this.s.ctx;c.passes=shipped?0:c.passes+1;c.pos++;if(c.passes>=this.s.count)this.beginStorage()}
 ship(i,x,useHarbor=true,useCaptain=true){const s=this.s,p=s.players[i],c=s.ctx;if(!c||!x||typeof x!=='object'||!['ship','wharf'].includes(x.kind))throw Error('出荷種別が正しくありません');if(!c.captainBonus)c.captainBonus={};if(!c.captainPrivilegeResolved)c.captainPrivilegeResolved={};let legal;if(x.kind==='ship'){legal=this.publicShipments(i).find(y=>y.good===x.good&&y.ship===x.ship&&y.qty===x.qty);if(!legal)throw Error('出荷できない組み合わせです');const sh=s.ships[legal.ship];sh.good=legal.good;sh.qty+=legal.qty}else{legal=this.wharfShipments(i).find(y=>y.good===x.good&&y.qty===x.qty);if(!legal)throw Error('造船所で出荷できない数量です');p.wharfUsed=true;s.goodsSupply[legal.good]+=legal.qty}p.goods[legal.good]-=legal.qty;let points=legal.qty;if(useHarbor&&active(p,'harbor'))points++;if(useCaptain&&i===s.currentChooser&&!c.captainPrivilegeResolved[i]){points++;c.captainBonus[i]=true;c.captainPrivilegeResolved[i]=true}p.vp+=points;s.vpSupply=Math.max(0,s.vpSupply-points);this.note(`${p.name}が${GOODS[legal.good].name}を${legal.qty}個出荷し${points}VP`)}
 beginStorage(){const s=this.s;s.ships.forEach(sh=>{if(sh.qty===sh.cap){s.goodsSupply[sh.good]+=sh.qty;sh.good=null;sh.qty=0}});s.phase='captainStorage';s.ctx.storagePos=0}
 storageStep(){const s=this.s,c=s.ctx;if(c.storagePos>=s.count){this.finishRole();return}const i=c.storagePos,p=s.players[i],types=GKEYS.filter(g=>p.goods[g]>0);if(!types.length){c.storagePos++;return}const slots=(active(p,'store1')?1:0)+(active(p,'store2')?2:0);if(p.human){s.pending={type:'storage',types,warehouseSlots:slots};return}this.store(i,this.aiStorage(i,types,slots));c.storagePos++}
 on_storage(plan){this.store(0,plan);this.s.ctx.storagePos++}
 store(i,plan){const s=this.s,p=s.players[i],slots=(active(p,'store1')?1:0)+(active(p,'store2')?2:0);if(!plan||!Array.isArray(plan.protectedTypes)||(plan.loose!==null&&!GKEYS.includes(plan.loose)))throw Error('保管内容が正しくありません');const protectedTypes=plan.protectedTypes;if(protectedTypes.some(g=>!GKEYS.includes(g)||p.goods[g]<=0)||new Set(protectedTypes).size!==protectedTypes.length||protectedTypes.length>slots)throw Error('倉庫に保管できない商品が含まれています');const loose=plan.loose;if(loose&&(!p.goods[loose]||protectedTypes.includes(loose)))throw Error('倉庫外で残す商品が正しくありません');for(const g of GKEYS){if(protectedTypes.includes(g))continue;const keep=g===loose?1:0;const discard=Math.max(0,p.goods[g]-keep);p.goods[g]-=discard;s.goodsSupply[g]+=discard}this.note(`${p.name}が商品を保管`)}
 resultRows(){return this.s.players.map((p,index)=>{const building=p.buildings.reduce((n,b)=>n+b.vp,0),bonus=this.largeBonus(p);return{index,name:p.name,shipping:p.vp,building,bonus,total:p.vp+building+bonus,tie:p.money+GKEYS.reduce((n,g)=>n+p.goods[g],0)}}).sort((a,b)=>b.total-a.total||b.tie-a.tie)}
 finishGame(){const s=this.s;s.phase='end';s.pending=null;s.ctx=null;const rows=this.resultRows();s.result=rows;const winners=rows.filter(x=>x.total===rows[0].total&&x.tie===rows[0].tie).map(x=>x.name);this.note(`ゲーム終了。${winners.length>1?'同点首位は':'勝者は'}${winners.join('・')}`)}
 largeBonus(p){let total=0;for(const b of p.buildings.filter(x=>x.large&&x.workers>0)){if(b.effect==='guild')total+=p.buildings.filter(x=>x.kind==='production').reduce((n,x)=>n+(x.smallProduction?1:2),0);if(b.effect==='residence'){const n=p.plants.length;total+=n>=12?7:n===11?6:n===10?5:4}if(b.effect==='fortress')total+=Math.floor(allColonists(p)/3);if(b.effect==='customs')total+=Math.floor(p.vp/4);if(b.effect==='cityhall')total+=p.buildings.filter(x=>x.violet).length}return total}
 roleValue(role,i){const p=this.s.players[i],goods=GKEYS.reduce((n,g)=>n+p.goods[g],0);if(role==='settler')return p.plants.length<12?3+(active(p,'hacienda')?2:0):0;if(role==='mayor')return Math.min(allColonists(p)+3,p.plants.length+p.buildings.length)+this.inactive(p);if(role==='builder')return Math.min(6,p.money)+this.affordable(i,i===this.s.chooser).length;if(role==='craftsman')return this.productionPotential(p)*1.5+(active(p,'factory')?3:0);if(role==='trader')return this.saleOptions(i).reduce((m,g)=>Math.max(m,GOODS[g].value+2),0);if(role==='captain')return Math.min(goods,6)+(active(p,'harbor')?2:0);return 2}
 aiRole(i){const opts=this.s.roles.filter(r=>!this.s.chosen.includes(r));let best=opts[0],bs=-1e9;for(const r of opts){let v=this.roleValue(r,i)+this.s.roleCoins[r]*2;if(this.s.difficulty!=='easy')v-=Math.max(...this.s.players.map((_,j)=>j===i?0:this.roleValue(r,j)))*.3;if(this.s.difficulty==='hard'){if(this.s.vpSupply<20&&r==='captain')v+=4;if(r==='mayor'&&this.s.endAfterRound)v-=3}if(v>bs){best=r;bs=v}}return best}
 roleAdvice(){const opts=this.s.roles.filter(r=>!this.s.chosen.includes(r)).map(r=>{const own=this.roleValue(r,0)+this.s.roleCoins[r]*2,opp=Math.max(...this.s.players.slice(1).map((_,j)=>this.roleValue(r,j+1)));return{r,own,opp,score:own-opp*.25}}).sort((a,b)=>b.score-a.score);const x=opts[0];return `候補は「${ROLES[x.r]}」。自分の利益${x.own.toFixed(1)}に対し、相手の最大便乗利益${x.opp.toFixed(1)}も差し引いて評価しています。`}
 explainRole(r,i){const own=this.roleValue(r,i),opp=Math.max(...this.s.players.map((_,j)=>j===i?0:this.roleValue(r,j)));return own>=opp?`自分の利益を優先しつつ、相手の便乗を抑えやすい選択です。`:`相手にも利益がありますが、現在の資金・商品・配置を優先した選択です。`}
 inactive(p){return p.plants.filter(x=>!x.worker).length+p.buildings.reduce((n,b)=>n+b.slots-b.workers,0)}
 productionPotential(p){let n=p.plants.filter(x=>x.worker&&x.good==='corn').length;for(const g of GKEYS.slice(1)){const farms=p.plants.filter(x=>x.worker&&x.good===g).length,cap=p.buildings.filter(b=>b.kind==='production'&&b.good===g).reduce((z,b)=>z+b.workers,0);n+=Math.min(farms,cap)}return n}
 buildingUtility(p,b){let v=b.vp*2+(b.violet?2:1);if(b.kind==='production'&&p.plants.some(x=>x.good===b.good))v+=5;if(b.effect==='factory')v+=this.productionPotential(p);if(b.effect==='harbor'||b.effect==='wharf')v+=GKEYS.reduce((n,g)=>n+p.goods[g],0);return v}
 aiUseHacienda(i){return this.s.players[i].plants.length<11&&this.s.difficulty!=='hard'}
 aiSettler(i,opts){if(this.s.difficulty==='easy')return opts[0];const p=this.s.players[i],score=x=>x.kind==='quarry'?(p.money>=4?5:2):2+(p.buildings.some(b=>b.kind==='production'&&b.good===x.good)?5:0)+GOODS[x.good].value;return [...opts].sort((a,b)=>score(b)-score(a))[0]}
 aiBuild(i,opts){if(!opts.length)return null;if(this.s.difficulty==='easy')return opts[0].id;const p=this.s.players[i];return [...opts].sort((a,b)=>this.buildingUtility(p,b)-this.buildingUtility(p,a))[0].id}
 aiGood(i,types){return [...types].sort((a,b)=>GOODS[b].value-GOODS[a].value)[0]}
 aiSell(i,opts){if(!opts.length)return null;return this.s.difficulty==='easy'?opts[0]:[...opts].sort((a,b)=>GOODS[b].value-GOODS[a].value)[0]}
 aiShip(i,pub,wharf){const all=[...pub,...wharf];if(!all.length)return null;if(!pub.length&&this.s.difficulty==='hard'&&this.s.vpSupply>20)return null;return all.sort((a,b)=>b.qty-a.qty||GOODS[b.good].value-GOODS[a.good].value)[0]}
 aiStorage(i,types,slots){const sorted=[...types].sort((a,b)=>this.s.players[i].goods[b]-this.s.players[i].goods[a]||GOODS[b].value-GOODS[a].value);const protectedTypes=sorted.slice(0,slots),loose=sorted.find(g=>!protectedTypes.includes(g))||null;return{protectedTypes,loose}}
}
return{Game,GOODS,GKEYS,ROLES,BUILDINGS,SETUP,active,citySpaces,allColonists};
});
