'use strict';
const assert=require('assert');
const {Game,allColonists}=require('../engine.js');
const {createTutorialGame,STEPS,snapshot,allowsAction,advanceAfterAction}=require('../tutorial.js');

function runLesson(){
  const g=createTutorialGame(),s=g.s,milestones={cornShipped:false,captainPrivilegeTaken:false};
  let stage='board';
  const next=()=>{assert(STEPS[stage].next,`no next at ${stage}`);stage=STEPS[stage].next};
  const act=(type,payload,want)=>{
    assert(allowsAction(stage,g.s,type,payload),`allowed ${stage}/${type}`);
    const before=snapshot(g.s);g.dispatch(type,payload);
    stage=advanceAfterAction(stage,type,payload,before,g.s,milestones);
    assert.equal(stage,want,`transition after ${type}`);
  };
  assert.equal(s.count,3);assert.equal(s.difficulty,'easy');assert.equal(s.players[0].money,2);
  assert.equal(s.schema,2);assert.equal(Object.hasOwn(s,'tutorial'),false);
  assert.equal(s.players[0].sanjuan,2);assert.equal(s.colonistReserve,53);
  assert.deepEqual(s.faceup,['corn','corn','corn','corn']);
  assert.equal(s.colonistReserve+s.colonistShip+s.players.reduce((n,p)=>n+allColonists(p),0),58);
  g.continue();next();next();
  assert(!allowsAction(stage,s,'role',{role:'builder'}));
  act('role',{role:'settler'},'corn');
  assert(!allowsAction(stage,s,'settler',{choice:{kind:'quarry'}}));
  act('settler',{choice:s.pending.options.find(x=>x.good==='corn')},'building-market');
  assert.equal(s.currentChooser,1);assert.equal(s.currentRole,'builder');next();
  assert(!allowsAction(stage,s,'builder',{id:'small_market'}));
  act('builder',{id:'sm_indigo'},'staff-indigo');
  assert.equal(s.players[0].money,1);assert.equal(s.currentChooser,2);assert.equal(s.pending.type,'staff');
  const me=s.players[0];
  me.plants[0].worker=1;me.sanjuan--;stage='staff-corn';
  me.plants[1].worker=1;me.sanjuan--;stage='staff-building';
  assert(!allowsAction(stage,s,'staff',{plants:[1,1],buildings:[0]}));
  me.buildings[0].workers=1;me.sanjuan--;stage='staff-confirm';
  act('staff',{plants:[1,1],buildings:[1]},'produce');
  assert.equal(s.round,2);assert.equal(s.currentChooser,1);assert.equal(s.currentRole,'craftsman');
  act('craftsmanProduce',{produce:true},'goods');
  assert.equal(me.goods.corn,1);assert.equal(me.goods.indigo,1);
  assert.equal(s.currentChooser,2);assert.equal(s.currentRole,'trader');
  assert.deepEqual(s.pending.options,['indigo']);assert.deepEqual(s.trade,['corn']);
  next();next();assert(!allowsAction(stage,s,'trader',{good:'corn'}));
  act('trader',{good:'indigo'},'money');
  assert.equal(me.money,2);assert.equal(me.goods.corn,1);assert.equal(me.goods.indigo,0);
  next();act('role',{role:'captain'},'ships-info');
  assert.equal(me.money,3,'captain has one role coin from round 1');next();
  assert(!allowsAction(stage,s,'captain',{choice:s.pending.options.find(x=>x.ship===1)}));
  act('captain',{choice:s.pending.options.find(x=>x.kind==='ship'&&x.good==='corn'&&x.ship===0)},'bonus');
  assert.equal(me.vp,1);assert.equal(me.goods.corn,0);assert(milestones.cornShipped);
  act('captainPrivilege',{use:true},'complete');
  assert.equal(me.vp,2);assert(milestones.captainPrivilegeTaken);
  assert.equal(s.round,3,'dispatch advances synchronously into the next round');
  assert.equal(s.phase,'builder','the tutorial can complete during an NPC role in round 3');
  assert.equal(s.pending.type,'builder');
  const promoted=Game.restore(s);
  assert.equal(Object.hasOwn(promoted,'aiRole'),false,'tutorial role override is removed');
  assert.equal(promoted.rng,Math.random,'normal RNG resumes');
  return JSON.parse(JSON.stringify(s));
}
const first=runLesson(),second=runLesson();
assert.deepEqual(first,second,'tutorial and NPC actions are reproducible');
const normal=new Game({count:3,rng:()=>.2});
assert.equal(Object.hasOwn(normal,'aiRole'),false);
assert.notDeepEqual(normal.s.faceup,first.faceup);
console.log('tutorial tests: all passed');
